version: "3"

services:
  oer-flask-api:
    image: laocoon667/oer-flask-api:latest
    ports:
      - "5000:5000"
    restart: on-failure

  oer-metadata-editor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: on-failure
